### ISSUE TITLE
Add Readme files to each folder

### ISSUE THREAD

**Issue by smiths** [smiths/swhs#1]
A Readme file should be added to each folder to explain the folder's contents.  In particular, the implementation folder should explain how to run and how to test the software.

**Comment by bmaclach** [comment]
I had assumed that this was for me to do, although I realize now that you never explicitly said that... Hopefully it's okay that I did them! Let me know if there is anything you think should be changed with them.

**Comment by smiths** [comment]
The Readme files look great.  Thank you.  I did have some issues in the testing folder, but I'll close this issue and open a new one.
