### ISSUE TITLE
(Drasil) Discrepancy between manual and Drasil SRS

### ISSUE THREAD

**Issue by lmawarid** [smiths/swhs#13]
In the Drasil-generated SRS (SWHS_SRS), there are three new symbols tau^L_P, tau^S_P and tau_W that are not referenced in the original SRS (PCM_SRS), and their descriptions only say "a constant". I think the descriptions should provide a bit more detail and possibly hint to where they are being used.

**Comment by bmaclach** [comment]
I've added these to the manual SRS, and provided more informative descriptions for both the manual and Drasil SRS.
