### ISSUE TITLE
(Drasil) Issues with the HTML SRS

### ISSUE THREAD

**Issue by lmawarid** [smiths/swhs#14]
A couple of issues with the HTML-format SRS:

- The definition links in assumptions A7, A8 and A9 are not active.
- In the Data Constraints section, 'Table 2' is not referenced to anything.

Other issues, but I believe these are just limitations to Drasil's current functionality (not too sure because I have not worked on it in a while):

- The image in the figure does not show up.
- Citations missing in Purpose of Document and Organization of Document.
- Irregular table widths in the Data Definitions section.
- Data Constraints - 'this Table' should be capitalized, but again, probably a Drasil issue.

**Comment by bmaclach** [comment]
The first three issues were issues with my code, and they are now fixed. The other three are limitations of Drasil, and so I've posted issues in that repo to address them.
