### ISSUE TITLE
Testing Folder

### ISSUE THREAD

**Issue by smiths** [smiths/swhs#2]
Running testMain.m does not work.  My guess is that this problem is caused by the test files being in a different folder from the Matlab files for swhs.

**Comment by bmaclach** [comment]
You were right, the major issue was that the files were moved to a different folder. testMain should work now. For me, all of the tests passed except for the tests that compare to the Fortran implementation (compareFortranTest.m), and the test that compares to a closed form solution (latentHeatTest.m).

The reason these ones are failing is because I don't have the output files from the Fortran implementation, or the text file that contains the results of the closed form solution.

**Comment by smiths** [comment]
I will e-mail you the FORTRAN program, to see if you can create the required test files.  With respect to the closed form solution, please delete that test case.  It is not worth the amount of effort it would take to reproduce.
Can you please clean up the Testing folder and remove all unnecessary files.  When I run testMain.m, it gets in an infinite loop and keeps rerunning all of the tests.  Maybe the test runner can explicitly mention the files to be tested, to remove this problem?

**Comment by bmaclach** [comment]
I cleaned out the Testing folder, and did as you suggested, specifying in testMain.m exactly which test functions to run. Hopefully that fixes the infinite loop problem. Let me know because I never experienced that problem, so I can't tell if it's fixed or not.

I also was able to use the Fortran files you gave me to generate the output files I needed. Those tests should work now. When I tried, all of the tests included in testMain.m passed.

**Comment by smiths** [comment]
Hello Brooks.  The changes you made have greatly improved the situation.  There is no longer an infinite loop.  Unfortunately the FORTRAN tests failed.  I will attach the full log of the test runner below.  I have a suspicion the the problem is due to different versions of Matlab.  My version is R2015b.
Best wishes.

*** Testing Output ***
>> testMain

tests = 

  Test with properties:

                  Name: 'compareSolversTest/testCompareSolvers'
      Parameterization: [0x0 matlab.unittest.parameters.EmptyParameter]
    SharedTestFixtures: [0x0 matlab.unittest.fixtures.EmptyFixture]
                  Tags: {1x0 cell}

Tests Include:
   0 Parameterizations, 0 Shared Test Fixture Classes, 0 Tags.

Running badInputTest
..........
..........
...
Done badInputTest
__________

Running invalidInputTest
..........
..........
..........
..........
....
Done invalidInputTest
__________

Running compareSolversTest
PCM has started to melt at time 3322.065744
PCM has finished melting at time 20571.368997
PCM has started to melt at time 3322.065744
PCM has finished melting at time 20571.368998

delta =

   3.3091e-08


delta =

   3.3876e-08


delta =

   2.4220e-07


delta =

   2.0652e-08


delta =

   9.5424e-08

.
Done compareSolversTest
__________

Running compareFortranTest
PCM has started to melt at time 3322.065744
PCM has finished melting at time 20571.368997

================================================================================
Error occurred in compareFortranTest/testFM1 and it did not run to completion.

    --------------
    Error Details:
    --------------
    Error using textscan
    Invalid file identifier. Use fopen to generate a valid file identifier.
    
    Error in PCM_Error (line 13)
    F = textscan(FfileID, '%f %f %f %f %f %f %f %f %f %f', 'Delimiter', ' ', 'MultipleDelimsAsOne', 1, 'Headerlines', 23);
    
    Error in compareFortranTest>testFM1 (line 31)
    delta = PCM_Error('F01.out', 'M01.out', 'Twat')
    
================================================================================
.PCM has started to melt at time 36195.839667
0.137138% of the PCM has melted at time 50000.000000

================================================================================
Error occurred in compareFortranTest/testFM2 and it did not run to completion.

    --------------
    Error Details:
    --------------
    Error using textscan
    Invalid file identifier. Use fopen to generate a valid file identifier.
    
    Error in PCM_Error (line 13)
    F = textscan(FfileID, '%f %f %f %f %f %f %f %f %f %f', 'Delimiter', ' ', 'MultipleDelimsAsOne', 1, 'Headerlines', 23);
    
    Error in compareFortranTest>testFM2 (line 59)
    delta = PCM_Error('F02.out', 'M02.out', 'Twat')
    
================================================================================
.PCM has started to melt at time 3322.065744
99.991870% of the PCM has melted at time 20570.000000

================================================================================
Error occurred in compareFortranTest/testFM3 and it did not run to completion.

    --------------
    Error Details:
    --------------
    Error using textscan
    Invalid file identifier. Use fopen to generate a valid file identifier.
    
    Error in PCM_Error (line 13)
    F = textscan(FfileID, '%f %f %f %f %f %f %f %f %f %f', 'Delimiter', ' ', 'MultipleDelimsAsOne', 1, 'Headerlines', 23);
    
    Error in compareFortranTest>testFM3 (line 87)
    delta = PCM_Error('F03.out', 'M03.out', 'Twat')
    
================================================================================
.PCM has started to melt at time 3322.065744
PCM has finished melting at time 20571.368997

================================================================================
Error occurred in compareFortranTest/testFM4 and it did not run to completion.

    --------------
    Error Details:
    --------------
    Error using textscan
    Invalid file identifier. Use fopen to generate a valid file identifier.
    
    Error in PCM_Error (line 13)
    F = textscan(FfileID, '%f %f %f %f %f %f %f %f %f %f', 'Delimiter', ' ', 'MultipleDelimsAsOne', 1, 'Headerlines', 23);
    
    Error in compareFortranTest>testFM4 (line 115)
    delta = PCM_Error('F04.out', 'M04.out', 'Twat')
    
================================================================================
.Warning: It is recommended that Vp be >= 0.0001 
> In verify_params (line 126)
  In main (line 21)
  In compareFortranTest>testFM5 (line 141)
  In matlab.unittest.FunctionTestCase/test (line 98)
  In matlab.unittest.TestRunner/evaluateMethodCore (line 1042)
  In matlab.unittest.TestRunner/evaluateMethodsOnTestContent (line 986)
  In matlab.unittest.TestRunner/runTestMethod (line 1327)
  In matlab.unittest.TestRunner/runTest (line 1282)
  In matlab.unittest.TestRunner/repeatTest (line 586)
  In matlab.unittest.TestRunner/runSharedTestCase (line 548)
  In matlab.unittest.TestRunner/runTestClass (line 1212)
  In matlab.unittest.TestRunner/invokeTestContentOperatorMethod_ (line 1079)
  In matlab.unittest.plugins.TestRunnerPlugin/runTestClass (line 378)
  In matlab.unittest.plugins.testrunprogress.ConciseProgressPlugin/runTestClass (line 68)
  In matlab.unittest.plugins.TestRunnerPlugin/invokeTestContentOperatorMethod_ (line 658)
  In matlab.unittest.TestRunner/evaluateMethodOnPlugins (line 945)
  In matlab.unittest.TestRunner/runTestSuite (line 1144)
  In matlab.unittest.TestRunner/invokeTestContentOperatorMethod_ (line 1079)
  In matlab.unittest.plugins.TestRunnerPlugin/runTestSuite (line 229)
  In matlab.unittest.plugins.FailureDiagnosticsPlugin/runTestSuite (line 95)
  In matlab.unittest.plugins.TestRunnerPlugin/invokeTestContentOperatorMethod_ (line 658)
  In matlab.unittest.TestRunner/evaluateMethodOnPlugins (line 945)
  In matlab.unittest.TestRunner/run (line 307)
  In runtests (line 103)
  In testMain (line 2) 
PCM has started to melt at time 3801.662039
PCM has finished melting at time 4525.711915
Warning: There is greater than 0.00001 relative error between the Ep output and the expected output based on
the law of conservation of energy. 
> In verify_output (line 85)
  In main (line 106)
  In compareFortranTest>testFM5 (line 141)
  In matlab.unittest.FunctionTestCase/test (line 98)
  In matlab.unittest.TestRunner/evaluateMethodCore (line 1042)
  In matlab.unittest.TestRunner/evaluateMethodsOnTestContent (line 986)
  In matlab.unittest.TestRunner/runTestMethod (line 1327)
  In matlab.unittest.TestRunner/runTest (line 1282)
  In matlab.unittest.TestRunner/repeatTest (line 586)
  In matlab.unittest.TestRunner/runSharedTestCase (line 548)
  In matlab.unittest.TestRunner/runTestClass (line 1212)
  In matlab.unittest.TestRunner/invokeTestContentOperatorMethod_ (line 1079)
  In matlab.unittest.plugins.TestRunnerPlugin/runTestClass (line 378)
  In matlab.unittest.plugins.testrunprogress.ConciseProgressPlugin/runTestClass (line 68)
  In matlab.unittest.plugins.TestRunnerPlugin/invokeTestContentOperatorMethod_ (line 658)
  In matlab.unittest.TestRunner/evaluateMethodOnPlugins (line 945)
  In matlab.unittest.TestRunner/runTestSuite (line 1144)
  In matlab.unittest.TestRunner/invokeTestContentOperatorMethod_ (line 1079)
  In matlab.unittest.plugins.TestRunnerPlugin/runTestSuite (line 229)
  In matlab.unittest.plugins.FailureDiagnosticsPlugin/runTestSuite (line 95)
  In matlab.unittest.plugins.TestRunnerPlugin/invokeTestContentOperatorMethod_ (line 658)
  In matlab.unittest.TestRunner/evaluateMethodOnPlugins (line 945)
  In matlab.unittest.TestRunner/run (line 307)
  In runtests (line 103)
  In testMain (line 2) 

================================================================================
Error occurred in compareFortranTest/testFM5 and it did not run to completion.

    --------------
    Error Details:
    --------------
    Error using textscan
    Invalid file identifier. Use fopen to generate a valid file identifier.
    
    Error in PCM_Error (line 13)
    F = textscan(FfileID, '%f %f %f %f %f %f %f %f %f %f', 'Delimiter', ' ', 'MultipleDelimsAsOne', 1, 'Headerlines', 23);
    
    Error in compareFortranTest>testFM5 (line 143)
    delta = PCM_Error('F01.out', 'M05.out', 'TwatNoP')
    
================================================================================
.
Done compareFortranTest
__________

Running energyTest
...
Done energyTest
__________

Running eventTest
.....
Done eventTest
__________

Running paramsTest

expParams = 

              L: 1.5000
           diam: 0.4120
             Vp: 0.0500
             Ap: 1.2000
          rho_p: 1007
          Tmelt: 44.2000
           C_ps: 1760
           C_pl: 2270
             Hf: 211600
             Ac: 0.1200
             Tc: 50
          rho_w: 1000
            C_w: 4186
             hc: 1000
             hp: 1000
          Tinit: 40
          tstep: 10
         tfinal: 50000
         AbsTol: 1.0000e-10
         RelTol: 1.0000e-10
             Vt: 0.2000
             Mw: 149.9749
          tau_w: 5.2316e+03
            eta: 10
             Mp: 50.3500
         tau_ps: 73.8467
         tau_pl: 95.2454
    Epmelt_init: 3.7219e+05
       Ep_melt3: 10654060
       Mw_noPCM: 199.9749
    tau_w_noPCM: 6.9758e+03


actParams = 

              L: 1.5000
           diam: 0.4120
             Vp: 0.0500
             Ap: 1.2000
          rho_p: 1007
          Tmelt: 44.2000
           C_ps: 1760
           C_pl: 2270
             Hf: 211600
             Ac: 0.1200
             Tc: 50
          rho_w: 1000
            C_w: 4186
             hc: 1000
             hp: 1000
          Tinit: 40
          tstep: 10
         tfinal: 50000
         AbsTol: 1.0000e-10
         RelTol: 1.0000e-10
             Vt: 0.2000
             Mw: 149.9749
          tau_w: 5.2316e+03
            eta: 10
             Mp: 50.3500
         tau_ps: 73.8467
         tau_pl: 95.2454
    Epmelt_init: 3.7219e+05
       Ep_melt3: 10654060
       Mw_noPCM: 199.9749
    tau_w_noPCM: 6.9758e+03

.
Done paramsTest
__________

Running temperatureTest
.
dTexp =

    0.0011         0

...
Done temperatureTest
__________

Running verifyOutputTest
....
Done verifyOutputTest
__________

Failure Summary:

     Name                        Failed  Incomplete  Reason(s)
    ===========================================================
     compareFortranTest/testFM1    X         X       Errored.
    -----------------------------------------------------------
     compareFortranTest/testFM2    X         X       Errored.
    -----------------------------------------------------------
     compareFortranTest/testFM3    X         X       Errored.
    -----------------------------------------------------------
     compareFortranTest/testFM4    X         X       Errored.
    -----------------------------------------------------------
     compareFortranTest/testFM5    X         X       Errored.
    
>> results

results = 

  1x90 TestResult array with properties:

    Name
    Passed
    Failed
    Incomplete
    Duration

Totals:
   85 Passed, 5 Failed, 5 Incomplete.
   42.0697 seconds testing time.

>>

**Comment by bmaclach** [comment]
Thanks for the error log. I realized I never committed the FORTRAN output files because they were being ignored. I modified the .gitignore file and committed the necessary .out files. Hopefully the tests work now!

**Comment by smiths** [comment]
The test cases now passed!  Very nice!  A small issue I noticed is that the warning messages for the conservation of energy hard codes the error threshold.  It would be better if this value was a configuration constant, or at least a named variable in the program.  Issuing warnings is a great idea.

**Comment by bmaclach** [comment]
Good to hear that the tests worked! I added the tolerance for conservation of energy as an input parameter, and modified the implementation and testing to accommodate that.

**Comment by smiths** [comment]
Great!  I think we can close this issue now.  :-)
