### ISSUE TITLE
C Code:  Remove system(...) calls

### ISSUE THREAD

**Issue by palmerst** [smiths/swhs#24]
The testing works better on Windows now that you have removed the system calls that execute **cp**, but you still have system calls causing issues (they try to execute **make** -- the make binary that is shipped with mingw is **mingw32-make**).

You should avoid making calls to system, especially for cross platform programs.  Perhaps put the necessary make commands into the makefile instead, using the $(MAKE) variable which stores the name by which **make** was invoked.

**Comment by bmaclach** [comment]
Made the suggested changes. I had to move the copy commands to the makefile as well because the copying needed to be done before make was called. I used a variable so that the appropriate copy command for the users OS is used.
