### ISSUE TITLE
Remove dlls and exe files from version control

### ISSUE THREAD

**Issue by smiths** [smiths/swhs#3]
Generated files do not normally go under version control.  Instead provide instructions for installing the required libraries.  The instructions, together with a makefile, should allow someone else to install the software on their system.

**Comment by bmaclach** [comment]
Does this also apply to the header files in the "cvode", "nvector", and "sundials" folders in SWHS/Program/CCode/include? Those headers were all part of the CVODE solver package, so if the user will be installing that on their system, they will have those headers as well. Thus, I would guess that I should remove them from this repo, but I want to be sure before I do.

**Comment by smiths** [comment]
The normal model is as you describe - the users install the dependencies, and then use the appropriate changes to the makefile to build their software.  However, I think we should try including the external source files in our repository, as you have done.  This way we can manage the version of the software, and we can manage the entire build process.  In the long term, it will be better to remove the external source files, but in the short term, they should help us with portability and installability.

**Comment by bmaclach** [comment]
All right, then I will just remove the dlls and exes and add some instructions for installation, as you originally posted.
