### ISSUE TITLE
PCM_SRS: Unclear Table Headers

### ISSUE THREAD

**Issue by elwazana** [smiths/swhs#32]
For the Table of Units, it is unclear what the second column "unit" is referring to, due to the entries being; length, mass, etc. While the third column has the actual "units".

**Comment by elwazana** [comment]
![image](https://user-images.githubusercontent.com/35268928/39711218-1608a3a6-51ed-11e8-9ef8-deed097d454c.png)

**Comment by smiths** [comment]
@elwazana, great question.  Unit is a reference to the concept that is being given a dimension.  It is measurement system agnostic.  The unit measures length, but it doesn't say which specific unit measure of length is being used.  The next column gives the SI units, but we could give the Imperial units instead.  That is, we could have a different column and the length unit as ft.
