### ISSUE TITLE
PSM_SRS: Improper Wording?

### ISSUE THREAD

**Issue by elwazana** [smiths/swhs#34]
In the DD4 table, the SI Units are said to be "dimensionless". I am unsure whether this is terminology I don't know. If it isn't "unitless" may be more accurate and constant.

**Comment by elwazana** [comment]
![image](https://user-images.githubusercontent.com/35268928/39711306-6168fac6-51ed-11e8-9cc4-06c9c4988139.png)

**Comment by smiths** [comment]
Dimensionless is the right term, since phi is the ratio of two quantities with the same units:

https://simple.wikipedia.org/wiki/Dimensionless_quantity
