### ISSUE TITLE
PCM_MIS: Double Write Typo

### ISSUE THREAD

**Issue by elwazana** [smiths/swhs#37]
In the last paragraph of section 2, towards the end of the paragraph, the phrase "to introduce to introduce" appears.

**Comment by elwazana** [comment]
1e0795d3e2459fa7acd8192adf934ae15bf1f8d4

**Comment by smiths** [comment]
Please do not close these issues until they have been reviewed.  We need to be systematic.  Corrections to the manual version may also have to be done to the stable (Drasil) version.  Please just identify the issues; do not fix them.

**Comment by smiths** [comment]
@elwazana, you were correct to make this correction.  In general we need to trace these changes through the Drasil (generated) version, but the MIS for PCM is not currently generated.  There are no further ramification for this change.  It is fine to close this issue.
