### ISSUE TITLE
PCM_MIS: Unclear Word

### ISSUE THREAD

**Issue by elwazana** [smiths/swhs#39]
In section 6.5, the word (getter) is used.  The context of its use is unclear so is its intended meaning.

**Comment by smiths** [comment]
Please include the text around the issue so that it can be assessed more easily.

**Comment by elwazana** [comment]
https://github.com/smiths/swhs/blob/0fa29b3812e325c38c69f9e99aed687a5938380d/MIS/PCM_MIS.tex#L480-L485

It's the first sentence of the subsection.

**Comment by smiths** [comment]
getters and setters are standard design terminology for object oriented programming.  We can leave the wording as getter.
