### ISSUE TITLE
PCM_VVPlan: Typo

### ISSUE THREAD

**Issue by elwazana** [smiths/swhs#42]
Section 5.2.1's Table has a typo on the 8th row in the first column.

**Comment by smiths** [comment]
Can you please show the table in the issue.  It will save time.  That way I don't have to open the document; I can just read the issue.  You should be able to extract a portion of the pdf for adding the image to your comment.  I don't know the best software for Windows for this, but one of your colleagues will very likely know.  Remember the goal is for me to be able to address the issue quickly.  Anything you can do to help that goal will be greatly appreciated.  😄

**Comment by elwazana** [comment]
**Table 2: Unrecommended Input Cases**

![image](https://user-images.githubusercontent.com/35268928/39630736-3eb4baf4-4f7e-11e8-9cec-4431b456c464.png)

**Comment by smiths** [comment]
This is very helpful @elwazana.  Please remove the typo.  (I assume we are talking about the extra 1 in the line.  Highlighting the typo would be even more helpful.)

You should also consider "bigger picture" issues.  I'm glad to see that you are on the V&V document.  Some questions to ask yourself when reading the testing sections:

- Is the motivation for the test case clear?
- Do the tests provide coverage?
- Could you reproduce the tests from the information given in the document?

**Comment by elwazana** [comment]
a7a1ba1c4d0ce1af7b73dced26ca7abcdedf530a
