### ISSUE TITLE
PCM_VVPlan: Symbols not Appearing

### ISSUE THREAD

**Issue by elwazana** [smiths/swhs#43]
![image](https://user-images.githubusercontent.com/35268928/39648978-2020dfda-4fb2-11e8-962a-82ddb85e9de5.png)

![image](https://user-images.githubusercontent.com/35268928/39648941-00a04d3a-4fb2-11e8-824c-9e96f2a31258.png)

These are only a few examples, but it seems that the tables in section 5.1.1 and 5.2.1 are not appropriately displaying the symbols in their third and fourth columns. It appears to be displaying the LaTeX annotations for the symbols but not the symbols themselves.

This seems to only happen in the third and fourth columns, the second column appears to display the symbols appropriately. 

I highlighted the error and underlined the correct symbols in column 2 with red.

**Comment by smiths** [comment]
@elwazana great observation, but this isn't actually an error.  The error message text only uses ASCII characters, so we represent the symbols in this way.  The response to the test case should be the program displaying this text.  Maybe at some point we will investigate unicode in the strings to make them closer to the mathematics, but this isn't a high priority right now.
