### ISSUE TITLE
Correct Comments in Python

### ISSUE THREAD

**Issue by samm82** [smiths/swhs#52]
In Python, comments are denoted by `#comment`, not by `"""comment"""`. Yes triple quotes can act as comments, but they actually create a multi-line string that is garbage collected if not used (ie. assigned to a variable, etc.). Depending on their placement, they can actually mess up the code. Comments throughout the Python Implementation should be replaced to reflect this, simply to follow convention if not to avoid errors.

smiths/caseStudies#86

**Comment by elwazana** [comment]
@smiths @samm82  I couldn't find any of these `"""comments"""` in this repositories Python files.

**Comment by smiths** [comment]
Great!
