### ISSUE TITLE
Undefined references when building using "make"

### ISSUE THREAD

**Issue by szymczdm** [smiths/swhs#8]
The following is what I see when attempting to make. I am following the directions in the README verbatim.

Note specifically the undefined references to certain functions. Is there a missing library in the makefile?

`gcc -std=c99 main.c load_params.c verify_params.c energy1.c energy2.c energy3.c verify_output.c output.c plot.c -I /usr/local/include -I /opt/local/include -I include -L /usr/local/lib -L /opt/local/lib -L ./lib -lsundials_cvode -lsundials_nvecserial -o swhs.out
plot.c: In function ‘plot’:
plot.c:34:5: warning: implicit declaration of function ‘popen’ [-Wimplicit-function-declaration]
     FILE *gnuplot = popen("gnuplot", "w");
     ^
plot.c:34:21: warning: initialization makes pointer from integer without a cast [enabled by default]
     FILE *gnuplot = popen("gnuplot", "w");
                     ^
/tmp/cckwEmDc.o: In function load_params':
load_params.c:(.text+0x238): undefined reference to pow'
/tmp/ccaENIAo.o: In function verify_recommended':
verify_params.c:(.text+0x4fd): undefined reference to pow'
./lib/libsundials_cvode.so: undefined reference to exp'
./lib/libsundials_cvode.so: undefined reference to sqrt'
collect2: error: ld returned 1 exit status
make: *** [swhs.out] Error 1`

**Comment by bmaclach** [comment]
As Luthfi discovered, changing the C compiler flag in the makefile from -std=c99 to -std=gnu99 fixes the errors related to the `popen` function.

As for the other errors (related to the `pow`, `exp`, and `sqrt` functions), apparently GCC does not automatically link to the math library in C, even if `#include <math.h>` is part of the code. Adding `-lm` to the library links in the makefile removed those errors.
